---
title: 'Global transpiration data from sap flow measurements: the SAPFLUXNET database'
subtitle: 'Authors and affiliations'
author: "R. Poyatos"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output:
  word_document: 
    reference_docx: word-styles-reference-01.docx
  html_document:
    df_print: paged
  pdf_document: 
    fig_caption: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(googlesheets4)
library(tidyverse)
# Function to get affiliations ranked from 
# 1 to n (this function was found on Stack Overflow)

rankID <- function(x){
  su=sort(unique(x))
  for (i in 1:length(su)) x[x==su[i]] = i
  return(x)
}

```

```{r read_data,echo=FALSE,include=FALSE,message=FALSE}

# read data from googlesheets
# use code to generate author list:
# https://audhalbritter.com/code-based-author-and-affiliation-list/


coauthor_data <- read_sheet('https://docs.google.com/spreadsheets/d/1MO43IQFSb7aB607u6RiZ6afgk97fwX8DIC4LvN2W1V8',
sheet='coauthor_data')


coauthor_data %>% 
  arrange(full_name) %>% 
  rownames_to_column('author_order') %>% 
  mutate(author_order=6+as.numeric(author_order))->coauthor_data

# Add main authors

main_authors <- tibble(
  author_order=1:6,
      full_name = c('Poyatos, Rafael','Granda, Víctor','Flo, Víctor',
                     'Steppe, Kathy','Mencuccini, Maurizio','Martínez-Vilalta, Jordi'),
       email=c('r.poyatos@creaf.uab.es','victorgrandagarcia@gmail.com',
               'v.flo@creaf.uab.cat','kathy.steppe@ugent.be','m.mencuccini@creaf.uab.cat',
               'jordi.martinez.vilata@uab.cat'),
       affiliation1=c('CREAF, E08193 Bellaterra (Cerdanyola del Vallès), Catalonia, Spain',
                      'CREAF, E08193 Bellaterra (Cerdanyola del Vallès), Catalonia, Spain',
                      'CREAF, E08193 Bellaterra (Cerdanyola del Vallès), Catalonia, Spain',
                      'Laboratory of Plant Ecology, Faculty of Bioscience Engineering, Ghent University, B‐9000 Ghent, Belgium',
                      'ICREA, Barcelona, Catalonia, Spain',
                      'CREAF, E08193 Bellaterra (Cerdanyola del Vallès), Catalonia, Spain'),
       affiliation2=c('Universitat Autònoma de Barcelona, E08193 Bellaterra, (Cerdanyola del Vallès), Catalonia, Spain',
                      'Joint Research Unit CREAF-CTFC, Bellaterra, Catalonia, Spain',
                      NA,NA,'CREAF, E08193 Bellaterra (Cerdanyola del Vallès), Catalonia, Spain',
                      'Universitat Autònoma de Barcelona, E08193 Bellaterra, (Cerdanyola del Vallès), Catalonia, Spain'),
       affiliation3=rep(NA,6),
       observations=rep(NA,6),
       ORCID=c('https://orcid.org/0000-0003-0521-2523','https://orcid.org/0000-0002-0469-1991',
               'https://orcid.org/0000-0003-1908-4577','https://orcid.org/0000-0001-6252-0704',
               'http://orcid.org/0000-0003-0840-1477','http://orcid.org/0000-0002-2332-7298')
)

main_authors[1:3,] %>% 
  bind_rows(coauthor_data) %>% 
  bind_rows(main_authors[4:6,]) %>% 
  select(-author_order) %>% 
  rownames_to_column('author_order') %>% 
  mutate_at('author_order',as.numeric)->all_authors


# Extract first and last names
all_authors %>% 
  mutate(last_name=sapply(strsplit(full_name,","),'[[',1),
         first_name=sapply(strsplit(full_name,","),'[[',2)
  ) %>% 
  select(author_order,full_name,first_name,last_name,everything())-> coauthor_data_names
         
# Gather affiliations

coauthor_data_names %>% 
  pivot_longer(cols=c('affiliation1','affiliation2','affiliation3'),
               names_to='num_affiliation',values_to='affiliation',
              names_prefix='affiliation', 
              names_transform=list(num_affiliation=as.numeric)) %>% 
  filter(!is.na(affiliation))-> coauthor_afflong


```


```{r build_list,echo=FALSE,include=FALSE,message=FALSE}

name_aff_list <- coauthor_afflong %>% 
  arrange(author_order, affiliation) %>% 
  rowwise() %>% 
  # extract the first letter of each first name and put a dot after each letter
  mutate(
    Initials = paste(stringi::stri_extract_all(regex = "\\b([[:alpha:]])", 
                                               str = first_name, simplify = TRUE), collapse = ". "),
    Initials = paste0(Initials, ".")) %>%
  ungroup() %>% 
  # add a column from 1 to n
  mutate(ID = 1:n()) %>%
  group_by(affiliation) %>% 
  # replace ID with min number (same affiliations become the same number)
  mutate(ID = min(ID)) %>% 
  ungroup() %>% 
  # use function above to assign new ID from 1 to n
  mutate(ID = rankID(ID)) %>%
  #Paste Last and Initials
  mutate(name = paste0(first_name, " ", last_name))

```



```{r authors_list, echo=FALSE,results='asis',message=FALSE}

# Create a list with all names
name_aff_list %>%   
  group_by(last_name, name,author_order) %>% 
  summarise(affs = paste(ID[order(ID)], collapse = ",")) %>% 
  arrange(author_order) %>% 
  mutate(
    affs = paste0("^", affs, "^"),
    nameID = paste0(name, affs)     
         ) %>% 
  pull(nameID) %>% 
  paste(collapse = ", ") %>% 
  cat(sep=", ")

```


```{r affiliation_list, echo=FALSE, results='asis'}

# Create a list with all Affiliations
name_aff_list%>% 
  distinct(ID, affiliation) %>% 
  arrange(ID) %>% 
  mutate(ID = paste0("^", ID, "^")) %>% 
  mutate(affiliation2 = paste(ID, affiliation, sep = ""), 
  affiliation3 = paste(ID, affiliation, sep = "")) %>% 
  pull(affiliation2) %>% 
   paste0(".  \n") %>%
  cat()
```

